# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r: bioc-release
warnings_are_errors: false
cache: packages

env:
  global:
    - R_CHECK_ARGS="--no-manual --as-cran"

matrix:
  before_install:
    - echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc
  include:
    - os: linux
      r: release
      before_deploy:
        - Rscript -e 'remotes::install_github("combiz/scFlow")'
        - Rscript -e 'install.packages("pkgdown")'
        - Rscript -e 'remotes::install_github("combiz/scFlowData")'
      deploy:
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE)'
        skip_cleanup: true
    - os: osx
      r: release
      fortran: false

addons:
  apt:
    packages:
      - libssl1.0.0
      - libcairo2-dev
      - libudunits2-dev
      - gdal-bin
      - proj-bin
      - libgdal-dev
      - libproj-dev
r_packages:
  - covr
  - lintr
r_github_packages:
  - combiz/RANN.L1
after_script:
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'lintr::lint_package()'
after_success:
  - Rscript -e 'covr::coveralls()'

stages:
  - name: deploy
    # require the branch name to be master (note for PRs this is the base branch name)
    if: branch = master

notifications:
  webhooks:
    on_success: always
    on_failure: never
    on_start: never
    on_cancel: never
    on_error: never
  email:
    recipients:
      - c.khozoie@imperial.ac.uk
      - n.skene@imperial.ac.uk
      - n.fancy@imperial.ac.uk
      - m.moradi@imperial.ac.uk
